In [1]:
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn import metrics


import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
# ignore warnings
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import env
import wrangle
import acquire
import split_scale


Gather

In [2]:
df = acquire.prep_iris()


In [ ]:
Split

In [7]:
#train_df, test_df = split_scale.split_my_data(df,train_ratio=.80,seed=123,stratify=df.species)

In [8]:
df.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [9]:
X = df[['sepal_length','sepal_width','petal_length','petal_width']]
y = df[['species']]

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .30, random_state = 123)

X_train.head()

sepal_length  sepal_width  petal_length  petal_width
114           5.8          2.8           5.1          2.4
136           6.3          3.4           5.6          2.4
53            5.5          2.3           4.0          1.3
19            5.1          3.8           1.5          0.3
38            4.4          3.0           1.3          0.2

In [11]:
y_train.head()

species
114        2
136        2
53         1
19         0
38         0

Create Basic Model


Create the logistic regression object


In [12]:
logit = LogisticRegression(C=1, class_weight={1:2}, random_state = 123, solver='saga')

Fit the model to the training data

In [13]:
logit.fit(X_train, y_train)

LogisticRegression(C=1, class_weight={1: 2}, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=123, solver='saga', tol=0.0001, verbose=0,
                   warm_start=False)

Print the coefficients and intercept of the model

In [14]:
print('Coefficient: \n', logit.coef_)
print('Intercept: \n', logit.intercept_)

Coefficient: 
 [[ 0.31763491  1.36929068 -2.27249822 -1.01356992]
 [ 0.4677593  -1.56683877  0.62576686 -1.36659429]
 [-1.60462287 -1.66808521  2.53963528  2.39510574]]
Intercept: 
 [ 0.63741882  1.36583115 -2.22864781]


Predict Labels

In [17]:
y_pred = logit.predict(X_train)
print(pd.DataFrame(confusion_matrix(y_train,y_pred)))

    0   1   2
0  32   0   0
1   0  40   0
2   0   8  25


In [18]:
print(classification_report(y_train,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        32
           1       0.83      1.00      0.91        40
           2       1.00      0.76      0.86        33

    accuracy                           0.92       105
   macro avg       0.94      0.92      0.92       105
weighted avg       0.94      0.92      0.92       105



Estimate the probability of a passenger surviving, using the training data

In [16]:
y_pred_proba = logit.predict_proba(X_train)

Evaluate Model

Compute the accuracy